/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";
import {Asset} from "expo-asset";
import usePromise from "react-promise-suspense";

function ReactModel(props) {
    const getUrl = async () => {
        const asset = Asset.fromModule(require("../../assets/react.gltf"));
        await asset.downloadAsync();
        return asset.localUri;
    };

    const url = usePromise(getUrl, []);

    const { nodes, materials } = useGLTF(url);

    // Using a remote url is also not gonna work
    // const { nodes, materials } = useGLTF('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/react-logo/model.gltf');

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                position={[0, 1.31, 0]}
                rotation={[0, Math.PI / 2, 0]}
                scale={0.27}
            >
                  <meshStandardMaterial color="hotpink" />

                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus001.geometry}
                    position={[0.34, -0.08, 0.02]}
                    rotation={[-0.16, 0, -Math.PI / 2]}
                    scale={[3.75, 1.47, 3]}
                >
                      <meshStandardMaterial color="hotpink" />
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus003.geometry}
                    position={[-0.04, -0.11, 0]}
                    rotation={[0.89, 0, -Math.PI / 2]}
                    scale={[3.75, 1.47, 3]}
                >
                      <meshStandardMaterial color="hotpink" />
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus002.geometry}
                    position={[-0.52, -0.1, 0.16]}
                    rotation={[-1.18, 0, -Math.PI / 2]}
                    scale={[3.75, 1.47, 3]}
                >
                      <meshStandardMaterial color="hotpink" />
                </mesh>
            </mesh>
        </group>
    );
}

export default ReactModel;
